/**
 * Configuration loader
 */
import { readFile } from 'fs/promises';
import { existsSync, readFileSync } from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { parse as parseYaml } from 'yaml';
import { OpenFluxConfig, OpenFluxConfigSchema } from './schema';
import { Logger } from '../utils/logger';

const logger = new Logger('Config');

/**
 * Determine whether it is a packaged Electron application
 */
const isPackaged = !(process as any).defaultApp && !!(process as any).resourcesPath;

/**
 * Get the directory where the executable file is located
 */
const exeDir = dirname(process.execPath);

/**
 * Build a list of configuration file search paths
 * After packaging, search the exe directory and user data directory first.
 */
function getConfigPaths(): string[] {
    const paths: string[] = [];

    if (isPackaged) {
        // After packaging: directory at the same level as exe (portable mode)
        paths.push(
            join(exeDir, 'openflux.yaml'),
            join(exeDir, 'openflux.yml'),
            join(exeDir, 'OpenFlux.yaml'),
            join(exeDir, 'OpenFlux.yml'),
            join(exeDir, 'OpenFlux.json'),
        );
    }

    // Development mode: current working directory (compatible with original behavior)
    const cwd = process.cwd();
    paths.push(
        join(cwd, 'openflux.yaml'),
        join(cwd, 'openflux.yml'),
        join(cwd, 'OpenFlux.yaml'),
        join(cwd, 'OpenFlux.yml'),
        join(cwd, 'OpenFlux.json'),
    );

    // Tauri sidecar mode: Backtrack to the project root directory based on the script file location
    // __dirname = gateway/src/config/ -> Backtrack 3 levels to the project root
    try {
        const scriptDir = typeof __dirname !== 'undefined'
            ? __dirname
            : dirname(fileURLToPath(import.meta.url));
        const projectRoot = resolve(scriptDir, '..', '..', '..');
        if (projectRoot !== cwd) {
            paths.push(
                join(projectRoot, 'openflux.yaml'),
                join(projectRoot, 'openflux.yml'),
                join(projectRoot, 'OpenFlux.yaml'),
            );
        }
    } catch { /* ignore */ }

    // Tauri sidecar mode: OPENFLUX_RESOURCE_DIR points to the Tauri resource directory
    // (set by process.rs). In macOS packaged builds this is the primary way to locate config.
    const tauriResourceDir = process.env.OPENFLUX_RESOURCE_DIR;
    if (tauriResourceDir) {
        paths.push(
            join(tauriResourceDir, 'openflux.yaml'),
            join(tauriResourceDir, 'openflux.yml'),
            join(tauriResourceDir, 'openflux.example.yaml'),
        );
    }

    // User directory
    const userProfile = process.env.USERPROFILE || process.env.HOME || '';
    if (userProfile) {
        paths.push(join(userProfile, '.openflux', 'config.yaml'));
        paths.push(join(userProfile, '.openflux', 'openflux.yaml'));
    }

    if (isPackaged) {
        // After packaging: Sample configuration in the resources directory (informal)
        paths.push(join((process as any).resourcesPath, 'openflux.example.yaml'));
    }

    return paths;
}

const CONFIG_PATHS = getConfigPaths();

/**
 * Candidate paths for the enterprise white-label baked config (openflux.brand.yaml).
 * Generated by build-brand.ps1 and bundled under resources/.brands/. It is merged as an
 * "overlay" onto the base config. It only carries differentiating fields like
 * nexusai / router / brandLock / agentPresets / memoryPresets and lacks a full llm config, so it is not
 * used as a standalone config file but layered on top of the base config.
 */
function getBrandOverlayPaths(): string[] {
    const paths: string[] = [];
    // Dev override: dev-brand.ps1 generates the overlay and points here.
    // In packaged builds exeDir/resourcesPath resolve it instead, so this stays empty.
    const envOverlay = process.env.OPENFLUX_BRAND_OVERLAY;
    if (envOverlay) {
        paths.push(envOverlay);
    }
    paths.push(
        join(exeDir, '.brands', 'openflux.brand.yaml'),
        join(exeDir, 'openflux.brand.yaml'),
    );
    // Dev sidecar mode: in `tauri dev` process.execPath is node.exe, so exeDir is useless. Back-track
    // from this script's location (gateway/src/config) to the project root and look there as well, so
    // dev-brand.ps1 can drop the overlay as a file and the gateway finds it WITHOUT relying on the
    // OPENFLUX_BRAND_OVERLAY env var surviving the pnpm/tauri/cargo/sidecar process chain.
    try {
        const scriptDir = typeof __dirname !== 'undefined'
            ? __dirname
            : dirname(fileURLToPath(import.meta.url));
        const projectRoot = resolve(scriptDir, '..', '..', '..');
        paths.push(
            join(projectRoot, '.brands', 'openflux.brand.yaml'),
            join(projectRoot, 'openflux.brand.yaml'),
        );
    } catch { /* ignore */ }
    // Tauri sidecar mode: OPENFLUX_RESOURCE_DIR is set by process.rs and points to
    // the Tauri resource dir (e.g. XCXD.app/Contents/Resources/ on macOS).
    const tauriResDir = process.env.OPENFLUX_RESOURCE_DIR;
    if (tauriResDir) {
        paths.push(
            join(tauriResDir, '.brands', 'openflux.brand.yaml'),
            join(tauriResDir, 'openflux.brand.yaml'),
        );
    }
    const resourcesPath = (process as any).resourcesPath;
    if (resourcesPath) {
        paths.push(
            join(resourcesPath, '.brands', 'openflux.brand.yaml'),
            join(resourcesPath, 'openflux.brand.yaml'),
        );
    }
    return paths;
}

/**
 * Last-resort dev fallback: derive the overlay directly from brand.json (OPENFLUX_BRAND_FILE).
 * The Rust process always receives OPENFLUX_BRAND_FILE (brand.rs reads it) and process.rs forwards
 * it to this sidecar, so this path works even when the PowerShell-generated overlay file/env var is
 * missing. It mirrors the brand.json -> overlay transform in dev-brand.ps1 / build-brand.ps1.
 */
function loadBrandOverlayFromBrandFile(): Record<string, unknown> | null {
    const brandFile = process.env.OPENFLUX_BRAND_FILE;
    if (!brandFile || !existsSync(brandFile)) return null;
    let brand: any;
    try {
        brand = JSON.parse(readFileSync(brandFile, 'utf-8'));
    } catch (e) {
        logger.warn(`Failed to parse brand.json: ${brandFile}`, e);
        return null;
    }
    const overlay: Record<string, unknown> = {};
    const svc = brand?.services;
    if (svc && typeof svc === 'object') {
        const nexusai: Record<string, unknown> = {};
        if (svc.nexusaiApiUrl) nexusai.apiUrl = svc.nexusaiApiUrl;
        if (svc.nexusaiWsUrl) nexusai.wsUrl = svc.nexusaiWsUrl;
        if (svc.atlasGatewayBaseUrl) nexusai.atlasGatewayBaseUrl = svc.atlasGatewayBaseUrl;
        if (Object.keys(nexusai).length > 0) overlay.nexusai = nexusai;

        if (svc.router?.url) {
            overlay.router = {
                url: svc.router.url,
                appType: svc.router.appType || 'openflux',
                ...(svc.router.appId ? { appId: svc.router.appId } : {}),
                ...(svc.router.apiKey ? { apiKey: svc.router.apiKey } : {}),
                enabled: svc.router.enabled !== undefined ? !!svc.router.enabled : true,
            };
        }
        if (svc.lockServices) overlay.brandLock = { services: true };
    }
    const brandLock = (overlay.brandLock as Record<string, unknown>) || {};
    if (brand?.setup?.skipWizard) brandLock.skipSetup = true;
    if (brand?.app?.identifier) brandLock.dataDir = brand.app.identifier;
    if (Object.keys(brandLock).length > 0) overlay.brandLock = brandLock;

    if (brand?.agents?.defaultName) overlay.agents = { globalAgentName: brand.agents.defaultName };
    if (Array.isArray(brand?.agents?.presets)) {
        const presets = brand.agents.presets.filter((p: any) => p?.name);
        if (presets.length > 0) overlay.agentPresets = presets;
    }
    if (Array.isArray(brand?.memories)) {
        const mems = brand.memories
            .filter((m: any) => m?.content)
            .map((m: any) => ({ content: m.content, ...(m.tags ? { tags: m.tags } : {}) }));
        if (mems.length > 0) overlay.memoryPresets = mems;
    }
    if (Object.keys(overlay).length === 0) return null;
    logger.info(`Derived brand overlay from brand.json: ${brandFile}`);
    return overlay;
}

/** Read and parse the white-label overlay config (returns null when absent) */
function loadBrandOverlay(): Record<string, unknown> | null {
    for (const path of getBrandOverlayPaths()) {
        if (!existsSync(path)) continue;
        try {
            const content = readFileSync(path, 'utf-8');
            const parsed = parseYaml(content) as Record<string, unknown> | null;
            if (parsed && typeof parsed === 'object') {
                logger.info(`Loaded brand overlay config from ${path}`);
                return parsed;
            }
        } catch (e) {
            logger.warn(`Failed to parse brand overlay config: ${path}`, e);
        }
    }
    // Dev fallback: no overlay file present -> derive straight from brand.json.
    return loadBrandOverlayFromBrandFile();
}

/** Merge the white-label overlay's differentiating fields into the raw config object (overlay wins) */
function applyBrandOverlay(rawConfig: Record<string, unknown>, overlay: Record<string, unknown>): void {
    // These are independent top-level keys; a shallow per-key merge is enough (overlay overrides base)
    // `agents` carries the brand default agent name (globalAgentName); merged shallowly so other
    // agents fields from the base config are preserved.
    for (const key of ['nexusai', 'router', 'brandLock', 'agents'] as const) {
        if (overlay[key] && typeof overlay[key] === 'object') {
            rawConfig[key] = { ...(rawConfig[key] as object || {}), ...(overlay[key] as object) };
        }
    }

    // agentPresets is replaced wholesale (array semantics)
    if (Array.isArray(overlay.agentPresets)) {
        rawConfig.agentPresets = overlay.agentPresets;

        // Also seed agents.list from presets if list is missing — without this,
        // the Zod schema rejects the config because agents.list is required (min 1).
        const agents = (rawConfig.agents || {}) as Record<string, unknown>;
        if (!Array.isArray(agents.list) || agents.list.length === 0) {
            const list = (overlay.agentPresets as any[]).map((p: any) => ({
                id: p.id || p.name?.toLowerCase().replace(/\s+/g, '-') || 'main',
                name: p.name || 'Main Agent',
                default: !!p.default,
                ...(p.systemPrompt ? { systemPrompt: p.systemPrompt } : {}),
            }));
            // Ensure at least one is marked default
            if (list.length > 0 && !list.some((a) => a.default)) {
                list[0]!.default = true;
            }
            agents.list = list;
            rawConfig.agents = agents;
        }
    }

    // Ensure agents.list always has at least one entry (required by schema)
    if (rawConfig.agents && typeof rawConfig.agents === 'object') {
        const agents = rawConfig.agents as Record<string, unknown>;
        if (!Array.isArray(agents.list) || agents.list.length === 0) {
            const name = (agents.globalAgentName as string) || 'Main Agent';
            agents.list = [{ id: 'main', name, default: true }];
        }
    }

    // memoryPresets (enterprise built-in memories) is replaced wholesale (array semantics)
    if (Array.isArray(overlay.memoryPresets)) {
        rawConfig.memoryPresets = overlay.memoryPresets;
    }
}

/**
 * Load configuration file
 */
export async function loadConfig(): Promise<OpenFluxConfig> {
    // Find configuration file
    let configPath: string | null = null;
    for (const path of CONFIG_PATHS) {
        if (existsSync(path)) {
            configPath = path;
            break;
        }
    }

    const brandOverlay = loadBrandOverlay();

    if (!configPath) {
        logger.warn('No config file found, using defaults');
        const defaults = getDefaultConfig();
        if (brandOverlay) {
            const merged = { ...defaults } as Record<string, unknown>;
            applyBrandOverlay(merged, brandOverlay);
            return OpenFluxConfigSchema.parse(merged);
        }
        return defaults;
    }

    try {
        const content = await readFile(configPath, 'utf-8');
        let rawConfig: unknown;

        if (configPath.endsWith('.json')) {
            rawConfig = JSON.parse(content);
        } else {
            rawConfig = parseYaml(content);
        }

        // Overlay the white-label baked config (nexusai / router / brandLock / agentPresets / memoryPresets), overlay wins
        if (brandOverlay && rawConfig && typeof rawConfig === 'object') {
            applyBrandOverlay(rawConfig as Record<string, unknown>, brandOverlay);
        }

        const config = OpenFluxConfigSchema.parse(rawConfig);

        // Merge providers configuration into llm configuration
        if (config.providers) {
            const mergeProvider = (llmConfig: any) => {
                const providerConfig = config.providers?.[llmConfig.provider];
                if (providerConfig) {
                    if (!llmConfig.apiKey && providerConfig.apiKey) {
                        llmConfig.apiKey = providerConfig.apiKey;
                    }
                    if (!llmConfig.baseUrl && providerConfig.baseUrl) {
                        llmConfig.baseUrl = providerConfig.baseUrl;
                    }
                }
            };
            mergeProvider(config.llm.orchestration);
            mergeProvider(config.llm.execution);
            if (config.llm.fallback) {
                mergeProvider(config.llm.fallback);
            }
        }

        logger.info(`Loaded config from ${configPath}`);
        return config;
    } catch (error) {
        logger.error(`Failed to load config from ${configPath}`, error);
        throw error;
    }
}

/**
 * Default configuration
 */
function getDefaultConfig(): OpenFluxConfig {
    return {
        llm: {
            orchestration: {
                provider: 'anthropic',
                model: 'claude-3-opus-20240229',
            },
            execution: {
                provider: 'openai',
                model: 'gpt-4o',
            },
        },
        remote: {
            enabled: false,
            host: 'localhost',
            port: 18801,
        },
        permissions: {
            autoApproveLevel: 1,
        },
        browser: {
            enabled: true,
            headless: false,
        },
        opencode: {
            enabled: true,
            autoApprove: false,
        },
        agents: {
            list: [{ id: 'main', name: 'Main Agent', default: true }],
        },
        memory: {
            enabled: true,
        },
    };
}
