/**
 * Forty-slide, domain-neutral stress fixture for deck-wide layout rhythm.
 *
 * The fixture deliberately exercises every non-image semantic family and all
 * currently supported native chart types. Copy stays short enough that the
 * test measures layout selection rather than automatic pagination.
 */
export const longFormSlides: Array<Record<string, unknown>> = [
    {
        purpose: '建立长篇报告的决策主题',
        message: '企业级 AI 扩张的核心不是增加试点，而是建立可重复的价值交付系统',
        composition: 'focal',
        body: '这份压力测试用四十页完整叙事检验跨章节节奏、版式变化与数据表达。',
    },
    {
        purpose: '章节转场：判断起点',
        message: '第一部分｜为什么现在必须改变扩张方式',
        composition: 'focal',
        layout: { archetype: 'section', variant: 'banded' },
    },
    {
        purpose: '提出核心判断',
        message: '试点数量增长很快，但真正进入稳定运营的比例仍然偏低',
        composition: 'narrative',
        body: '问题已经从“能否使用模型”转向“能否持续交付业务结果”。大量项目完成了演示，却没有形成负责人、稳定指标和持续运营机制。',
    },
    {
        purpose: '解释管理含义',
        message: '当所有项目都依赖少数专家时，新增需求只会放大交付瓶颈',
        composition: 'narrative',
        body: '当前工作方式把需求理解、数据准备、质量验证和上线运营集中在同一批核心人员身上。规模扩大后，这些隐性依赖会同时表现为排期变长、返工增加和负责人疲劳。',
        bullets: ['能力没有形成标准供给', '业务团队缺少自助判断框架', '上线后的持续运营责任不清晰'],
        layout: { archetype: 'editorial', variant: 'asymmetric' },
    },
    {
        purpose: '给出结构化解释',
        message: '规模化能力由业务场景、共享平台和运营机制三层共同构成',
        composition: 'narrative',
        body: '任何一层缺失，项目都会重新退回一次性交付。',
        bullets: ['业务场景定义结果与边界', '共享平台沉淀模型、工具和治理能力', '运营机制持续观察价值、成本与风险'],
        layout: { archetype: 'editorial', variant: 'banded' },
    },
    {
        purpose: '突出一个关键数字',
        message: '真正进入稳定运营的项目仍不到全部试点的一半',
        composition: 'data',
        information_role: 'status',
        metrics: [{ value: '38%', label: '稳定运营率', description: '测试数据，仅用于验证版式' }],
        layout: { archetype: 'evidence', variant: 'spotlight' },
    },
    {
        purpose: '并列三项经营证据',
        message: '价值、交付速度和复用率共同决定试点能否规模化',
        composition: 'data',
        information_role: 'evidence',
        metrics: [
            { value: '1.8×', label: '价值提升', description: '相对现有流程的示例指数' },
            { value: '6周', label: '平均上线周期', description: '从确认范围到投产' },
            { value: '54%', label: '能力复用率', description: '共享组件的示例占比' },
        ],
    },
    {
        purpose: '形成管理状态总览',
        message: '需求增长已经快于平台产能，治理覆盖仍是主要缺口',
        composition: 'data',
        information_role: 'status',
        metrics: [
            { value: '42', label: '在途需求' },
            { value: '17', label: '活跃试点' },
            { value: '9', label: '稳定运营' },
            { value: '63%', label: '治理覆盖' },
        ],
    },
    {
        purpose: '验证柱状图版式',
        message: '高价值场景已经集中在少数业务域',
        composition: 'data',
        chart: { type: 'column', name: '场景价值指数', labels: ['客户运营', '供应链', '知识工作', '财务'], values: [86, 74, 61, 43] },
        body: '测试数据用于观察柱状图、结论栏和跨页视觉语言的一致性。',
    },
    {
        purpose: '验证折线图版式',
        message: '共享能力投入后，单位场景交付周期连续下降',
        composition: 'data',
        chart: { type: 'line', name: '平均交付周期', labels: ['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6'], values: [12, 11, 9, 8, 7, 6] },
        body: '趋势用于检验时间序列表达。',
    },
    {
        purpose: '验证横向排名图版式',
        message: '客户运营和供应链最适合进入下一批规模化验证',
        composition: 'data',
        information_role: 'ranking',
        chart: { type: 'bar', name: '规模化准备度', labels: ['客户运营', '供应链', '知识工作', '财务', '人力资源'], values: [91, 83, 68, 57, 49] },
        body: '准备度综合价值、数据可用性和流程稳定性。',
    },
    {
        purpose: '验证饼图版式',
        message: '当前成本主要集中在模型调用与人工复核',
        composition: 'data',
        chart: { type: 'pie', name: '运营成本构成', labels: ['模型调用', '人工复核', '平台运行', '数据维护'], values: [38, 31, 18, 13] },
        body: '结构数据仅用于验证占比图。',
    },
    {
        purpose: '章节转场：目标系统',
        message: '第二部分｜把一次性交付改造成可重复系统',
        composition: 'focal',
        layout: { archetype: 'section', variant: 'banded' },
    },
    {
        purpose: '展示三步工作流',
        message: '每个场景先证明价值，再固化能力，最后移交持续运营',
        composition: 'sequence',
        steps: [
            { title: '证明价值', description: '冻结对象、指标和对照基线' },
            { title: '固化能力', description: '沉淀可复用流程和质量标准' },
            { title: '移交运营', description: '明确业务负责人和异常机制' },
        ],
    },
    {
        purpose: '展示里程碑时间线',
        message: '十二周验证分成四个决策门，任何一门失败都可以停止',
        composition: 'sequence',
        information_role: 'timeline',
        steps: [
            { title: '第1周', description: '确认业务结果' },
            { title: '第3周', description: '完成数据与风险评估' },
            { title: '第6周', description: '验证最小方案' },
            { title: '第9周', description: '完成真实流程试运行' },
            { title: '第12周', description: '决定扩大、调整或停止' },
        ],
    },
    {
        purpose: '验证纵向长标题流程',
        message: '上线不是终点，四项持续运营动作必须形成固定节奏',
        composition: 'sequence',
        steps: [
            { title: '每周复核关键业务指标与异常样本', description: '确认价值和质量没有持续偏离' },
            { title: '每月评估模型、工具和数据成本变化', description: '发现单位任务成本的结构性变化' },
            { title: '每季度重新验证风险边界与人工兜底', description: '确保自动化范围与真实风险一致' },
            { title: '每半年决定继续投入、迁移或停止能力', description: '避免低价值能力长期占用资源' },
        ],
        layout: { archetype: 'process', variant: 'stacked' },
    },
    {
        purpose: '比较两种组织方式',
        message: '平台团队应提供共性能力，业务团队必须拥有结果责任',
        composition: 'comparison',
        comparison: {
            left: { heading: '平台团队', items: ['模型与工具供给', '安全和质量标准', '成本与运行基础设施'] },
            right: { heading: '业务团队', items: ['场景选择与结果指标', '流程改变与用户采用', '异常处置与持续运营'] },
        },
    },
    {
        purpose: '验证包含式对比版式',
        message: '从项目制转向产品制后，管理对象和成功标准都会变化',
        composition: 'comparison',
        comparison: {
            left: { heading: '项目制', items: ['以交付日期为终点', '团队围绕单一需求临时组建', '复用依靠个人经验'] },
            right: { heading: '产品制', items: ['以持续业务结果为目标', '能力和责任长期存在', '复用通过标准供给完成'] },
        },
        layout: { archetype: 'comparison', variant: 'cards' },
    },
    {
        purpose: '展示双项集合',
        message: '第一阶段只建设两类最能解除瓶颈的共享供给',
        composition: 'grid',
        items: [
            { title: '场景评估包', description: '统一判断价值、数据、风险和运营准备度' },
            { title: '上线护栏包', description: '统一质量阈值、人工兜底和运行观测' },
        ],
    },
    {
        purpose: '展示非对称集合',
        message: '五项基础能力共同决定平台能否真正降低边际成本',
        composition: 'grid',
        items: [
            { title: '模型路由', description: '依据任务选择质量和成本组合' },
            { title: '工具接入', description: '用统一权限与审计连接业务系统' },
            { title: '知识供给', description: '保持来源、版本和责任可追踪' },
            { title: '质量评估', description: '覆盖离线、在线与人工复核' },
            { title: '运行观测', description: '追踪价值、风险、性能和成本' },
        ],
        layout: { archetype: 'collection', variant: 'asymmetric' },
    },
    {
        purpose: '验证紧凑阅读列表',
        message: '六项平台原则必须在所有场景中保持一致',
        composition: 'grid',
        information_role: 'collection',
        items: [
            { title: '最小权限' }, { title: '来源可追踪' }, { title: '结果可评估' },
            { title: '失败可恢复' }, { title: '成本可解释' }, { title: '责任可定位' },
        ],
    },
    {
        purpose: '验证带状阅读列表',
        message: '八个交付检查点组成上线前的最小证据链',
        composition: 'grid',
        information_role: 'collection',
        items: [
            { title: '业务基线' }, { title: '目标指标' }, { title: '数据责任' }, { title: '风险边界' },
            { title: '质量阈值' }, { title: '人工兜底' }, { title: '运行告警' }, { title: '退出条件' },
        ],
        layout: { archetype: 'collection', variant: 'banded' },
    },
    {
        purpose: '验证事件台账',
        message: '试运行的一周必须记录关键事件和处置结果',
        composition: 'grid',
        information_role: 'events',
        items: [
            { title: '周一 09:00', description: '开放首批业务用户' },
            { title: '周二 14:30', description: '修正分类边界' },
            { title: '周三 11:20', description: '调整人工复核阈值' },
            { title: '周四 16:10', description: '验证失败恢复流程' },
            { title: '周五 15:00', description: '完成价值与风险复盘' },
        ],
    },
    {
        purpose: '验证来源索引',
        message: '所有关键判断都必须能够回到可追踪的证据来源',
        composition: 'grid',
        information_role: 'sources',
        items: [
            { title: '业务流程基线', description: '流程负责人确认的当前状态' },
            { title: '历史任务样本', description: '经过脱敏与代表性检查' },
            { title: '试运行观测', description: '真实用户与真实工作负载' },
            { title: '成本账单', description: '模型、平台和人工复核成本' },
            { title: '风险记录', description: '异常、处置与剩余风险' },
        ],
    },
    {
        purpose: '章节转场：经营机制',
        message: '第三部分｜用经营机制持续管理价值、风险和成本',
        composition: 'focal',
        layout: { archetype: 'section', variant: 'banded' },
    },
    {
        purpose: '用引语建立原则',
        message: '规模化不是复制更多项目，而是让每个新增场景更容易成功',
        composition: 'quote',
        quote: '当新增需求不再线性增加专家投入时，平台化才真正开始。',
        attribution: '长篇回归测试观点',
    },
    {
        purpose: '解释经营单元',
        message: '每个稳定运行的能力都应有价值账户、风险账户和成本账户',
        composition: 'narrative',
        body: '三个账户使用不同指标，但必须由同一个业务负责人综合判断是否继续投入。价值账户回答结果是否发生，风险账户回答边界是否可控，成本账户回答投入是否值得持续。',
    },
    {
        purpose: '解释跨部门复盘',
        message: '月度复盘只讨论偏差、原因和行动，不重新展示全部运行数据',
        composition: 'narrative',
        body: '有效复盘从目标差异开始，随后判断偏差来自业务变化、模型能力、工具依赖还是流程采用，最后形成有负责人和截止时间的行动。',
        bullets: ['价值偏差决定是否调整场景', '质量偏差决定是否收紧边界', '成本偏差决定是否改变路由或流程'],
        layout: { archetype: 'editorial', variant: 'editorial' },
    },
    {
        purpose: '再次检验单指标节奏',
        message: '单个稳定场景应在三个月内证明持续价值',
        composition: 'data',
        information_role: 'status',
        metrics: [{ value: '90天', label: '价值验证窗口', description: '超过窗口仍无证据则重新评估' }],
        layout: { archetype: 'evidence', variant: 'spotlight' },
    },
    {
        purpose: '再次检验多指标节奏',
        message: '价值、质量和成本必须同时进入绿色区间',
        composition: 'data',
        information_role: 'evidence',
        metrics: [
            { value: '+24%', label: '目标流程效率' },
            { value: '96%', label: '关键任务合格率' },
            { value: '-18%', label: '单位任务成本' },
        ],
    },
    {
        purpose: '再次验证柱状图跨章节一致性',
        message: '平台复用率提升后，新增场景的边际投入明显下降',
        composition: 'data',
        chart: { type: 'column', name: '新增场景投入指数', labels: ['场景1', '场景2', '场景3', '场景4', '场景5'], values: [100, 82, 71, 59, 48] },
        body: '示例指数用于检验重复图表在长篇中的节奏变化。',
    },
    {
        purpose: '再次验证折线图跨章节一致性',
        message: '稳定运营后，人工复核应逐步集中到高风险任务',
        composition: 'data',
        chart: { type: 'line', name: '人工复核率', labels: ['上线', '第1月', '第2月', '第3月', '第4月'], values: [52, 43, 34, 26, 21] },
        body: '下降必须建立在质量阈值持续满足的前提上。',
    },
    {
        purpose: '比较治理方式',
        message: '统一底线比统一所有实现更适合多业务域扩张',
        composition: 'comparison',
        comparison: {
            left: { heading: '统一实现', items: ['短期一致性较高', '难以适应业务差异', '平台容易成为排期瓶颈'] },
            right: { heading: '统一底线', items: ['保留场景实现自由', '关键风险必须满足共同标准', '责任边界更容易扩展'] },
        },
    },
    {
        purpose: '给出经营动作',
        message: '四个动作把月度复盘结果转化为下一周期的实际改变',
        composition: 'sequence',
        steps: [
            { title: '保留', description: '继续运行并观察' },
            { title: '扩大', description: '增加用户或场景范围' },
            { title: '调整', description: '改变模型、工具或流程边界' },
            { title: '停止', description: '关闭低价值或高风险能力' },
        ],
    },
    {
        purpose: '章节转场：落地计划',
        message: '第四部分｜用两个季度建立规模化基础',
        composition: 'focal',
        layout: { archetype: 'section', variant: 'banded' },
    },
    {
        purpose: '展示十项行动清单',
        message: '首个季度只完成能够降低后续边际成本的十项基础工作',
        composition: 'grid',
        information_role: 'collection',
        items: [
            { title: '场景组合' }, { title: '价值基线' }, { title: '治理底线' }, { title: '模型路由' }, { title: '工具接入' },
            { title: '知识来源' }, { title: '质量评估' }, { title: '运行观测' }, { title: '成本账户' }, { title: '复盘节奏' },
        ],
    },
    {
        purpose: '用第二个引语形成收束',
        message: '最好的平台不是替团队做所有决定，而是让正确决定更容易重复',
        composition: 'quote',
        quote: '标准负责守住底线，业务负责创造结果。',
        attribution: '规模化原则',
    },
    {
        purpose: '给出最终执行节奏',
        message: '六个月计划先建立底座，再验证两个业务域，最后决定扩大范围',
        composition: 'sequence',
        information_role: 'timeline',
        steps: [
            { title: '第1月', description: '冻结标准与责任' },
            { title: '第2月', description: '上线共享供给' },
            { title: '第3—4月', description: '验证两个业务域' },
            { title: '第5月', description: '复盘价值、风险与成本' },
            { title: '第6月', description: '决定扩大、调整或停止' },
        ],
    },
    {
        purpose: '形成行动型收尾',
        message: '批准两个季度的基础建设与业务验证窗口',
        composition: 'closing',
        body: '首个决策门确认三件事：标准可执行、共享能力被复用、两个业务域产生持续价值。',
        layout: { archetype: 'closing' },
    },
    {
        purpose: '形成极简最终页',
        message: '用可重复的系统，替代不可扩张的英雄式交付',
        composition: 'closing',
        layout: { archetype: 'closing', variant: 'centered' },
    },
];
