/**
 * OpenFlux Cloud Chat Bridge
 * Bridge OpenFlux Roundtable WebSocket chat protocol to internal AgentProgressEvent
 *
 * Agreement format:
 *   Command: --NEXUSAI-INSTRUCTION-[cmd, data]-- (also compatible with --OpenFlux-INSTRUCTION-)
 *   Plain text: AI streaming reply snippets
 *
 * Chat process: ENTER (enter the chat room) -> INPUT (send a message) -> receive
 */

import WebSocket from 'ws';
import { existsSync, readFileSync, writeFileSync, unlinkSync, statSync, mkdirSync } from 'fs';
import { basename, dirname } from 'path';
import { Logger } from '../utils/logger';

/** Max size for a single file upload: 15 MiB (chatroom service limit) */
const MAX_UPLOAD_SIZE = 15 * 1024 * 1024;

const log = new Logger('OpenFluxChatBridge');

// ========================
// type definition
// ========================

/** OpenFlux connection configuration */
export interface OpenFluxCloudConfig {
    apiUrl: string;   // https://nexus-api.atyun.com (login/user_info)
    wsUrl: string;    // wss://nexus-chat.atyun.com
    atlasGatewayBaseUrl: string; // Atlas Model Egress root address (for environment signature isolation)
}

interface OpenFluxEnvSignature {
    apiUrl: string;
    wsUrl: string;
    atlasGatewayBaseUrl: string;
}

interface PersistedLoginState {
    token?: string;
    username?: string;
    atlasRuntime?: AtlasOpenFluxRuntime | null;
    env?: OpenFluxEnvSignature;
}

/** OpenFlux Agent information */
export interface OpenFluxAgent {
    agentId: number;
    appId: number;
    name: string;
    description?: string;
    chatroomId: number;
    avatar?: string;
}

/** OpenFlux chat history messages */
export interface OpenFluxChatHistoryMessage {
    role: 'user' | 'assistant';
    content: string;
    createdAt: number;
    agentName?: string;
}

/** Chat progress event (bridged to Gateway's event format) */
export interface OpenFluxChatProgressEvent {
    type: 'iteration' | 'tool_start' | 'tool_result' | 'thinking' | 'token' | 'cloud_files';
    tool?: string;
    args?: Record<string, unknown>;
    result?: unknown;
    token?: string;
    description?: string;
    /** When type === 'cloud_files': files generated by the Agent (from WITHFILECONTENTLIST / skill result file_list) */
    files?: Array<{ name: string; url: string }>;
}

/** OpenFlux file upload result */
export interface OpenFluxUploadResult {
    fileId: number;
    name: string;
    extension: string;
    size: number;
    mimeType: string;
    /** URL for frontend display / download */
    pathShow: string;
}

/** WebSocket request within a chatroom */
interface ChatroomRequest {
    message: string;
    onProgress: (event: OpenFluxChatProgressEvent) => void;
    resolve: (output: string) => void;
    reject: (error: Error) => void;
    /** Optional file IDs to attach with this message (FILELIST command) */
    fileIds?: number[];
}

interface ChatroomConnection {
    ws: WebSocket;
    chatroomId: number;
    ready: boolean;
    /** Whether the chat is currently ongoing (to prevent concurrency in the same chat room) */
    busy: boolean;
    /** The request currently being executed (reject when used for close) */
    currentRequest: ChatroomRequest | null;
    /** Queuing requests */
    queue: ChatroomRequest[];
}

// ========================
// OpenFluxChatBridge
// ========================

/**
 * Clean protocol markup and internal thought fragments from cloud message content.
 * Some agents in the cloud will wrap the thinking content in <<>>...<<>> / <><>...<><> and spit it out as ordinary text.
 */
export function cleanOpenFluxCloudText(content: string): string {
    const cleaned = content
        .replace(/--(?:NEXUSAI|OpenFlux)-INSTRUCTION-\[.*?\]--/g, '')
        .trim();
    const filter = createOpenFluxCloudTextFilter();
    return (filter.push(cleaned) + filter.flush())
        .trim();
}

const OPEN_THINKING_MARKERS = ['<thinking>', '<think>', '<<>>', '<><>'];
const XML_CLOSE_THINKING_MARKERS = ['</thinking>', '</think>'];

type ThinkingMarker = { index: number; token: string; closing: RegExp | string };

function markerPrefixTailLength(text: string, markers: string[]): number {
    const lowerText = text.toLowerCase();
    const lowerMarkers = markers.map(m => m.toLowerCase());
    const maxLength = Math.min(text.length, Math.max(...markers.map(m => m.length)) - 1);

    for (let length = maxLength; length > 0; length--) {
        const suffix = lowerText.slice(-length);
        if (lowerMarkers.some(marker => marker.startsWith(suffix))) return length;
    }

    return 0;
}

function findFirstThinkingStart(text: string): ThinkingMarker | null {
    const xml = text.match(/<think(?:ing)?>/i);
    const candidates: Array<ThinkingMarker | null> = [
        xml ? { index: xml.index ?? -1, token: xml[0], closing: /<\/think(?:ing)?>/i } : null,
        { index: text.indexOf('<<>>'), token: '<<>>', closing: '<<>>' },
        { index: text.indexOf('<><>'), token: '<><>', closing: '<><>' },
    ];
    const markers = candidates.filter((m): m is ThinkingMarker => Boolean(m) && m.index >= 0);

    if (markers.length === 0) return null;
    return markers.sort((a, b) => a.index - b.index)[0];
}

function findClosing(text: string, closing: RegExp | string): { index: number; length: number } | null {
    if (typeof closing === 'string') {
        const index = text.indexOf(closing);
        return index >= 0 ? { index, length: closing.length } : null;
    }

    const match = text.match(closing);
    return match ? { index: match.index ?? 0, length: match[0].length } : null;
}

/**
 * Streaming text filter: Avoid thinking tags leaking across WebSocket chunks.
 */
export function createOpenFluxCloudTextFilter(): { push: (chunk: string) => string; flush: () => string } {
    let buffer = '';
    let hiddenClosing: RegExp | string | null = null;

    const push = (chunk: string): string => {
        buffer += chunk;
        let output = '';

        while (buffer.length > 0) {
            if (hiddenClosing) {
                const end = findClosing(buffer, hiddenClosing);
                if (!end) {
                    const closingMarkers = typeof hiddenClosing === 'string'
                        ? [hiddenClosing]
                        : XML_CLOSE_THINKING_MARKERS;
                    const tailSize = markerPrefixTailLength(buffer, closingMarkers);
                    buffer = tailSize > 0 ? buffer.slice(-tailSize) : '';
                    break;
                }
                buffer = buffer.slice(end.index + end.length);
                hiddenClosing = null;
                continue;
            }

            const start = findFirstThinkingStart(buffer);
            if (!start) {
                const tailSize = markerPrefixTailLength(buffer, OPEN_THINKING_MARKERS);
                if (tailSize > 0) {
                    output += buffer.slice(0, -tailSize);
                    buffer = buffer.slice(-tailSize);
                } else {
                    output += buffer;
                    buffer = '';
                }
                break;
            }

            output += buffer.slice(0, start.index);
            buffer = buffer.slice(start.index + start.token.length);
            hiddenClosing = start.closing;
        }

        return output;
    };

    const flush = (): string => {
        if (hiddenClosing) {
            buffer = '';
            hiddenClosing = null;
            return '';
        }
        const output = buffer;
        buffer = '';
        return output;
    };

    return { push, flush };
}

/** Runtime configuration issued by Atlas for OpenFlux local Agent */
export interface AtlasOpenFluxRuntimeAbility {
    model_id: number;
    model_config_id: number;
    model_name: string;
    protocol: 'openai' | 'anthropic' | 'google';
    supplier_name: string;
    display_name: string;
}

export interface AtlasOpenFluxRuntime {
    chat: AtlasOpenFluxRuntimeAbility;
    embedding?: AtlasOpenFluxRuntimeAbility;
    /** Image generation ability (requests are relayed via the Atlas egress image endpoint) */
    image?: AtlasOpenFluxRuntimeAbility;
}

export type FetchUserInfoResultStatus =
    | 'updated'
    | 'unchanged'
    | 'unavailable'
    | 'auth_expired'
    | 'failed';

export interface FetchUserInfoResult {
    status: FetchUserInfoResultStatus;
    runtime?: AtlasOpenFluxRuntime | null;
    message?: string;
    httpStatus?: number;
}

function buildRuntimeSignature(runtime: AtlasOpenFluxRuntime | null): string | null {
    if (!runtime?.chat) return null;
    return JSON.stringify({
        chat: {
            protocol: runtime.chat.protocol,
            model_id: runtime.chat.model_id,
            model_config_id: runtime.chat.model_config_id,
            model_name: runtime.chat.model_name,
        },
        embedding: runtime.embedding ? {
            protocol: runtime.embedding.protocol,
            model_id: runtime.embedding.model_id,
            model_config_id: runtime.embedding.model_config_id,
            model_name: runtime.embedding.model_name,
        } : null,
        image: runtime.image ? {
            protocol: runtime.image.protocol,
            model_id: runtime.image.model_id,
            model_config_id: runtime.image.model_config_id,
            model_name: runtime.image.model_name,
        } : null,
    });
}

export class OpenFluxChatBridge {
    private config: OpenFluxCloudConfig;
    private token: string | null = null;
    private username: string | null = null;
    /** OpenFlux local Agent runtime configuration delivered by Atlas */
    private atlasRuntime: AtlasOpenFluxRuntime | null = null;
    /** Reuse connection by chat room ID */
    private connections = new Map<number, ChatroomConnection>();
    /** Token persistence file path */
    private tokenFile: string | null = null;

    constructor(config: OpenFluxCloudConfig, tokenFile?: string) {
        this.config = config;
        this.tokenFile = tokenFile || null;
        // Try to restore the persistent login state
        if (this.tokenFile) {
            this.restoreToken();
        }
    }

    private getEnvSignature(): OpenFluxEnvSignature {
        return {
            apiUrl: this.config.apiUrl,
            wsUrl: this.config.wsUrl,
            atlasGatewayBaseUrl: this.config.atlasGatewayBaseUrl,
        };
    }

    private isSameEnvSignature(savedEnv?: OpenFluxEnvSignature): boolean {
        if (!savedEnv) return false;
        const currentEnv = this.getEnvSignature();
        return savedEnv.apiUrl === currentEnv.apiUrl
            && savedEnv.wsUrl === currentEnv.wsUrl
            && savedEnv.atlasGatewayBaseUrl === currentEnv.atlasGatewayBaseUrl;
    }

    private closeAllConnections(): void {
        for (const [chatroomId, conn] of this.connections) {
            try {
                conn.ws.close();
            } catch { /* ignore */ }
            log.info(`Closing chatroom connection: ${chatroomId}`);
        }
        this.connections.clear();
    }

    private resetLoginState(logMessage: string): void {
        this.closeAllConnections();
        this.token = null;
        this.username = null;
        this.atlasRuntime = null;
        this.clearSavedToken();
        log.info(logMessage);
    }

    // ========================
    // Certification
    // ========================

    /** Restore token and atlas runtime from file */
    private restoreToken(): void {
        if (!this.tokenFile) return;
        try {
            if (existsSync(this.tokenFile)) {
                const saved = JSON.parse(readFileSync(this.tokenFile, 'utf-8')) as PersistedLoginState;
                if (!this.isSameEnvSignature(saved.env)) {
                    log.info('Ignored saved NexusAI login state due to environment mismatch');
                    return;
                }
                if (saved.token && saved.username) {
                    this.token = saved.token;
                    this.username = saved.username;
                    if (saved.atlasRuntime) {
                        this.atlasRuntime = saved.atlasRuntime;
                        log.info('Restored atlas runtime config', { chat_protocol: saved.atlasRuntime.chat?.protocol });
                    }
                    log.info('Restored NexusAI login state', { username: saved.username });
                }
            }
        } catch {
            log.warn('Failed to restore NexusAI login state');
        }
    }

    /** Persistence token and atlas runtime to file */
    private saveToken(): void {
        if (!this.tokenFile || !this.token || !this.username) return;
        try {
            writeFileSync(this.tokenFile, JSON.stringify({
                token: this.token,
                username: this.username,
                atlasRuntime: this.atlasRuntime,
                env: this.getEnvSignature(),
            }), 'utf-8');
        } catch { /* ignore */ }
    }

    /** Delete persistent files */
    private clearSavedToken(): void {
        if (!this.tokenFile) return;
        try {
            if (existsSync(this.tokenFile)) {
                unlinkSync(this.tokenFile);
            }
        } catch { /* ignore */ }
    }

    /** Log in to OpenFlux */
    async login(username: string, password: string): Promise<{ success: boolean; message?: string }> {
        try {
            const resp = await fetch(`${this.config.apiUrl}/v1/auth/login`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                body: new URLSearchParams({ username, password }),
            });

            if (!resp.ok) {
                const errText = await resp.text();
                log.error('Login failed', { status: resp.status, body: errText });
                return { success: false, message: `HTTP ${resp.status}: ${errText}` };
            }

            const data = await resp.json();
            this.token = data.access_token || data.token;
            this.username = username;

            if (!this.token) {
                return { success: false, message: '响应中无 token' };
            }

            // Automatically obtain user_info after successful login (including atlas runtime configuration)
            await this.fetchUserInfo();

            // Persistent login state (including atlas runtime)
            this.saveToken();

            log.info('OpenFlux login successful', { username, hasAtlasRuntime: !!this.atlasRuntime });
            return { success: true };
        } catch (error) {
            const msg = error instanceof Error ? error.message : String(error);
            log.error('OpenFlux login error', { error: msg });
            return { success: false, message: msg };
        }
    }

    /** Log out (clear all connections) */
    async logout(): Promise<void> {
        this.resetLoginState('OpenFlux logged out');
    }

    /** Clear the login state when authentication fails (such as invalid_token), but it does not mean that the user actively logs out */
    invalidateAuth(): void {
        this.resetLoginState('OpenFlux login state invalidated');
    }

    /** Get login status */
    getStatus(): { loggedIn: boolean; username?: string } {
        return {
            loggedIn: !!this.token,
            username: this.username || undefined,
        };
    }

    /** Get the current access_token (used in atlas_managed mode) */
    getToken(): string | null {
        return this.token;
    }

    /** Obtain the OpenFlux runtime configuration issued by Atlas */
    getAtlasRuntime(): AtlasOpenFluxRuntime | null {
        return this.atlasRuntime;
    }

    /**
     * Call GET /v1/auth/user_info to get atlas_openflux_runtime
     * V2 document requirements: This interface must be called after logging in
     */
    async fetchUserInfo(): Promise<FetchUserInfoResult> {
        if (!this.token) {
            return { status: 'failed', message: 'Not logged in to OpenFlux' };
        }
        const previousSignature = buildRuntimeSignature(this.atlasRuntime);
        try {
            const resp = await fetch(`${this.config.apiUrl}/v1/auth/user_info`, {
                method: 'GET',
                headers: this.getAuthHeaders(),
            });
            if (!resp.ok) {
                let detail = '';
                try {
                    const text = await resp.text();
                    const parsed = JSON.parse(text);
                    detail = parsed?.detail || text || '';
                } catch {
                    detail = '';
                }
                if (resp.status === 401 && detail.toLowerCase().includes('invalid_token')) {
                    log.warn('fetchUserInfo auth expired', { status: resp.status, detail });
                    return {
                        status: 'auth_expired',
                        httpStatus: resp.status,
                        message: detail || 'invalid_token',
                    };
                }
                log.warn('fetchUserInfo failed', { status: resp.status, detail });
                return {
                    status: 'failed',
                    httpStatus: resp.status,
                    message: detail || `HTTP ${resp.status}`,
                };
            }
            const result = await resp.json() as any;
            const runtime = result?.data?.atlas_openflux_runtime;
            if (runtime?.chat) {
                this.atlasRuntime = runtime as AtlasOpenFluxRuntime;
                const nextSignature = buildRuntimeSignature(this.atlasRuntime);
                log.info('Fetched atlas_openflux_runtime', {
                    chat_protocol: runtime.chat.protocol,
                    chat_model: runtime.chat.model_name,
                    embedding_protocol: runtime.embedding?.protocol,
                });
                // Update persistence files
                this.saveToken();
                return {
                    status: previousSignature === nextSignature ? 'unchanged' : 'updated',
                    runtime: this.atlasRuntime,
                };
            } else {
                log.info('user_info has no atlas_openflux_runtime (user may not have Atlas access)');
                this.atlasRuntime = null;
                this.saveToken();
                return {
                    status: 'unavailable',
                    runtime: null,
                };
            }
        } catch (err) {
            const message = err instanceof Error ? err.message : String(err);
            log.warn('fetchUserInfo error', { error: message });
            return {
                status: 'failed',
                message,
            };
        }
    }

    /** Get the current token (internal use) */
    private getAuthHeaders(): Record<string, string> {
        if (!this.token) throw new Error('Not logged in to OpenFlux');
        return { 'Authorization': `Bearer ${this.token}` };
    }

    // ========================
    // Agent information
    // ========================

    /** Get Agent list */
    async getAgentList(): Promise<OpenFluxAgent[]> {
        const headers = this.getAuthHeaders();
        const resp = await fetch(
            `${this.config.apiUrl}/v1/agent/agent_list?page=1&page_size=50&agent_search_type=1`,
            { headers }
        );

        if (!resp.ok) {
            throw new Error(`Failed to get Agent list: HTTP ${resp.status}`);
        }

        const result = await resp.json();
        const list = result.data?.list || result.data || [];

        const mapped = list.map((item: any) => ({
            agentId: item.agent_id,
            appId: item.app_id,
            name: item.name || item.agent_name || `Agent ${item.agent_id}`,
            description: item.description || item.agent_description || '',
            chatroomId: item.agent_chatroom_id || 0,
            avatar: item.avatar || '',
        }));

        // Remove duplicates by appId (API may return duplicate records)
        const seen = new Set<number>();
        return mapped.filter((a: OpenFluxAgent) => {
            if (seen.has(a.appId)) return false;
            seen.add(a.appId);
            return true;
        });
    }

    /** Get single Agent information (including chatroom_id) */
    async getAgentInfo(appId: number): Promise<OpenFluxAgent | null> {
        const headers = this.getAuthHeaders();
        const resp = await fetch(
            `${this.config.apiUrl}/v1/agent/agent_info/${appId}?publish_status=1`,
            { headers }
        );

        if (!resp.ok) return null;

        const result = await resp.json();
        const data = result.data;
        if (!data) return null;

        const agent = data.agent || {};
        const app = data.app || {};

        return {
            agentId: agent.agent_id || 0,
            appId: app.app_id || appId,
            name: app.name || `Agent ${appId}`,
            description: app.description || '',
            chatroomId: data.agent_chatroom_id || 0,
            avatar: app.avatar || '',
        };
    }

    // ========================
    // Chat history
    // ========================

    /** Get chat room history messages */
    async getChatHistory(chatroomId: number, page: number = 1, pageSize: number = 20): Promise<OpenFluxChatHistoryMessage[]> {
        const headers = this.getAuthHeaders();
        const resp = await fetch(
            `${this.config.apiUrl}/v1/chat/chat_message_list?chatroom_id=${chatroomId}&page=${page}&page_size=${pageSize}`,
            { headers }
        );

        if (!resp.ok) {
            log.warn('Failed to get chat history', { chatroomId, status: resp.status });
            return [];
        }

        const result = await resp.json();
        const list = result.data?.list || result.data || [];

        return list.map((item: any) => ({
            role: item.role === 'agent' || item.role === 'assistant' ? 'assistant' as const : 'user' as const,
            content: cleanOpenFluxCloudText(item.content || item.message || ''),
            createdAt: item.created_at ? new Date(item.created_at).getTime() : Date.now(),
            agentName: item.agent_name || item.nickname || undefined,
        }));
    }

    // ========================
    // File upload
    // ========================

    /**
     * Upload a single local file to the chatroom service and return its file_id, etc.
     * API: POST /v1/upload/upload_file (multipart/form-data, field name "file")
     */
    async uploadFile(filePath: string): Promise<OpenFluxUploadResult> {
        if (!this.token) throw new Error('Not logged in to OpenFlux');
        if (!existsSync(filePath)) {
            throw new Error(`File not found: ${filePath}`);
        }

        const size = statSync(filePath).size;
        if (size > MAX_UPLOAD_SIZE) {
            throw new Error(`File exceeds 15MiB limit: ${basename(filePath)} (${size} bytes)`);
        }

        const buffer = readFileSync(filePath);
        const fileName = basename(filePath);

        const form = new FormData();
        // Node 18+ global FormData/Blob: wrap file bytes in a Blob, third arg is the filename
        form.append('file', new Blob([buffer]), fileName);

        // Note: do not set Content-Type manually, fetch adds the multipart boundary automatically
        const resp = await fetch(`${this.config.apiUrl}/v1/upload/upload_file`, {
            method: 'POST',
            headers: this.getAuthHeaders(),
            body: form,
        });

        if (!resp.ok) {
            const errText = await resp.text().catch(() => '');
            throw new Error(`File upload failed: HTTP ${resp.status} ${errText}`);
        }

        const result = await resp.json() as any;
        if (result?.code !== 0 || !result?.data?.file_id) {
            throw new Error(`File upload failed: ${result?.detail || JSON.stringify(result)}`);
        }

        const data = result.data;
        log.info('File uploaded to OpenFlux', { fileId: data.file_id, name: fileName, size });
        return {
            fileId: data.file_id,
            name: data.name,
            extension: data.extension,
            size: data.size,
            mimeType: data.mime_type,
            pathShow: data.path_show,
        };
    }

    /**
     * Download a remote file to a local path (used to materialize Agent-generated files as local artifacts).
     * The URL is an absolute address returned by the chatroom service; the Bearer token is sent in case auth is required.
     * @returns number of bytes written
     */
    async downloadFile(url: string, destPath: string): Promise<number> {
        const resp = await fetch(url, {
            headers: this.token ? { Authorization: `Bearer ${this.token}` } : {},
        });
        if (!resp.ok) {
            throw new Error(`File download failed: HTTP ${resp.status} ${url}`);
        }
        const buffer = Buffer.from(await resp.arrayBuffer());
        mkdirSync(dirname(destPath), { recursive: true });
        writeFileSync(destPath, buffer);
        log.info('Downloaded cloud file', { url, destPath, size: buffer.length });
        return buffer.length;
    }

    // ========================
    // WebSocket Chat
    // ========================

    /**
     * Send chat message
     * If the chat room connection already exists and is idle, reuse the connection; otherwise create a new connection.
     * Requests for the same chat room will be queued and executed serially.
     * @param fileIds Optional file IDs (obtained from uploadFile) to attach with this message
     */
    async chat(
        chatroomId: number,
        message: string,
        onProgress: (event: OpenFluxChatProgressEvent) => void,
        fileIds?: number[],
    ): Promise<string> {
        if (!this.token) throw new Error('Not logged in to OpenFlux');

        return new Promise<string>((resolve, reject) => {
            const request = { message, onProgress, resolve, reject, fileIds };

            let conn = this.connections.get(chatroomId);

            if (conn && conn.ws.readyState === WebSocket.OPEN) {
                if (conn.busy) {
                    // queue with chat room
                    conn.queue.push(request);
                    log.info(`Chatroom ${chatroomId} busy, queued (queue length: ${conn.queue.length})`);
                } else {
                    // Direct execution
                    this.executeChat(conn, request);
                }
            } else {
                // New connection required
                if (conn) {
                    try { conn.ws.close(); } catch { /* ignore */ }
                    this.connections.delete(chatroomId);
                }
                this.createConnection(chatroomId, request);
            }
        });
    }

    /** Create a WebSocket connection and enter the chat room */
    private createConnection(
        chatroomId: number,
        firstRequest: ChatroomConnection['queue'][0],
    ): void {
        const wsUrl = `${this.config.wsUrl}/?token=${this.token}`;
        const ws = new WebSocket(wsUrl);

        const conn: ChatroomConnection = {
            ws,
            chatroomId,
            ready: false,
            busy: false,
            currentRequest: null,
            queue: [],
        };

        this.connections.set(chatroomId, conn);

        // Heartbeat keep-alive: Send ping every 30 seconds to prevent the server from closing the connection due to idleness
        const pingInterval = setInterval(() => {
            if (ws.readyState === WebSocket.OPEN) {
                try { ws.ping(); } catch { /* ignore */ }
            }
        }, 30_000);

        ws.on('open', () => {
            log.info(`WebSocket connected: chatroom ${chatroomId}`);
            // Enter the chat room
            ws.send(JSON.stringify(['ENTER', chatroomId]));
            // Set desktop mode
            ws.send(JSON.stringify(['ISDESKTOP', true]));

            // Wait briefly for ENTER confirmation before starting the first request
            setTimeout(() => {
                conn.ready = true;
                this.executeChat(conn, firstRequest);
            }, 500);
        });

        ws.on('error', (error) => {
            log.error(`WebSocket connection error: chatroom ${chatroomId}`, { error });
            clearInterval(pingInterval);
            // Reject currently active requests
            if (conn.currentRequest) {
                conn.currentRequest.reject(new Error(`WebSocket 连接失败: ${error.message}`));
                conn.currentRequest = null;
            } else {
                firstRequest.reject(new Error(`WebSocket 连接失败: ${error.message}`));
            }
            this.connections.delete(chatroomId);
        });

        ws.on('close', () => {
            log.info(`WebSocket connection closed: chatroom ${chatroomId}`);
            clearInterval(pingInterval);
            // Reject the currently active request (key fix: only the queue was processed before, and the executing request was missed)
            if (conn.currentRequest) {
                conn.currentRequest.reject(new Error('WebSocket 连接已关闭'));
                conn.currentRequest = null;
            }
            // Deny all queued requests
            for (const req of conn.queue) {
                req.reject(new Error('WebSocket 连接已关闭'));
            }
            conn.queue = [];
            conn.busy = false;
            this.connections.delete(chatroomId);
        });
    }

    /** Perform chat on existing connection */
    private executeChat(
        conn: ChatroomConnection,
        request: ChatroomConnection['queue'][0],
    ): void {
        conn.busy = true;
        conn.currentRequest = request;
        const { message, onProgress, resolve, reject } = request;
        const fullReply: string[] = [];
        const textFilter = createOpenFluxCloudTextFilter();
        let chatTimeout: ReturnType<typeof setTimeout> | null = null;

        // Idle timeout: a long agent run with many tool calls can take a while, but the server
        // keeps sending messages. Reset the timer on every incoming message so we only abort
        // after a real stall (no activity for IDLE_TIMEOUT_MS).
        const IDLE_TIMEOUT_MS = 10 * 60 * 1000;
        const armTimeout = () => {
            if (chatTimeout) clearTimeout(chatTimeout);
            chatTimeout = setTimeout(() => {
                cleanup();
                reject(new Error('Chat timed out (no activity for 10 minutes)'));
                this.processNextInQueue(conn);
            }, IDLE_TIMEOUT_MS);
        };
        armTimeout();

        const cleanup = () => {
            conn.ws.removeListener('message', messageHandler);
            conn.currentRequest = null;
            if (chatTimeout) {
                clearTimeout(chatTimeout);
                chatTimeout = null;
            }
        };

        const emitTextChunk = (chunk: string) => {
            const text = textFilter.push(chunk);
            if (text.length > 0) {
                fullReply.push(text);
                onProgress({ type: 'token', token: text });
            }
        };

        const messageHandler = (data: WebSocket.Data) => {
            const raw = data.toString();
            if (raw.length === 0) return;

            // Any activity from the server resets the idle timeout
            armTimeout();

            // Parse protocol instructions (compatible with NEXUSAI-INSTRUCTION and OpenFlux-INSTRUCTION)
            // A message may contain multiple instructions and text fragments, which need to be parsed piece by piece.
            const instructionRegex = /--(?:NEXUSAI|OpenFlux)-INSTRUCTION-(\[.*?\])--/g;
            let hasInstruction = false;
            let lastIndex = 0;
            let m: RegExpExecArray | null;

            while ((m = instructionRegex.exec(raw)) !== null) {
                hasInstruction = true;
                // If there is text before the command, it will be counted as an AI reply fragment.
                if (m.index > lastIndex) {
                    const textBefore = raw.slice(lastIndex, m.index);
                    if (textBefore.length > 0) {
                        emitTextChunk(textBefore);
                    }
                }
                lastIndex = m.index + m[0].length;

                try {
                    const instruction = JSON.parse(m[1]);
                    const cmd = instruction[0];
                    const cmdData = instruction.length > 1 ? instruction[1] : null;
                    log.info(`WS command: ${cmd}`, { chatroomId: conn.chatroomId });

                    this.handleInstruction(cmd, cmdData, onProgress, fullReply, () => {
                        // ENDCHAT callback: chat ended
                        const rest = textFilter.flush();
                        if (rest.length > 0) {
                            fullReply.push(rest);
                            onProgress({ type: 'token', token: rest });
                        }
                        log.info('ENDCHAT received, resolving Promise', {
                            chatroomId: conn.chatroomId,
                            replyLength: fullReply.join('').length,
                        });
                        cleanup();
                        const output = fullReply.join('');
                        resolve(output);
                        this.processNextInQueue(conn);
                    }, () => {
                        // ERROR callback
                        cleanup();
                        reject(new Error(`OpenFlux 错误: ${JSON.stringify(cmdData)}`));
                        this.processNextInQueue(conn);
                    });
                } catch (e) {
                    log.warn('Failed to parse command', { raw: raw.slice(0, 200) });
                }
            }

            if (!hasInstruction) {
                // Plain text stream - AI reply snippet (line breaks preserved to maintain Markdown formatting)
                emitTextChunk(raw);
            } else if (lastIndex < raw.length) {
                // The text after the last command
                const trailing = raw.slice(lastIndex);
                if (trailing.length > 0) {
                    emitTextChunk(trailing);
                }
            }
        };

        conn.ws.on('message', messageHandler);

        // When files are attached, send FILELIST (file ID list) before INPUT
        const fileIds = request.fileIds;
        if (fileIds && fileIds.length > 0) {
            log.info(`Sending FILELIST to chatroom ${conn.chatroomId}`, { fileIds });
            conn.ws.send(JSON.stringify(['FILELIST', fileIds]));
        }

        // Send message
        log.info(`Sending message to chatroom ${conn.chatroomId}`, { message: message.slice(0, 100) });
        conn.ws.send(JSON.stringify(['INPUT', message]));
    }

    /** Handle OpenFlux instructions */
    private handleInstruction(
        cmd: string,
        data: any,
        onProgress: (event: OpenFluxChatProgressEvent) => void,
        _fullReply: string[],
        onEndChat: () => void,
        onError: () => void,
    ): void {
        switch (cmd) {
            case 'OK':
                // Confirmation response for ENTER/ISDESKTOP/MCPTOOLLIST/SETABILITY/FILELIST (ignored)
                break;

            case 'CHAT':
                // User message confirmation (no need to push to client)
                break;

            case 'WITHFILELIST':
                // List of file details sent by the user (the desktop side does not process file display yet)
                break;

            case 'WITHFILECONTENTLIST':
                // Files/images generated by the Agent — emit as artifacts, downloaded/materialized by the caller
                if (data && Array.isArray(data) && data.length > 0) {
                    log.info('Agent sent files', { count: data.length });
                    const files = data
                        .filter((f: any) => f && typeof f.url === 'string')
                        .map((f: any) => ({ name: String(f.name || ''), url: String(f.url) }));
                    if (files.length > 0) {
                        onProgress({ type: 'cloud_files', files });
                    }
                }
                break;

            case 'REPLY':
                // Agent is about to start replying (data = Agent ID)
                onProgress({ type: 'iteration', description: `Agent ${data} 开始回复` });
                break;

            case 'ABILITY':
                // The ability used by Agent for this reply (data = ability ID, ignored on desktop)
                break;

            case 'TEXT':
                // Agent is about to send plain text (a new text bubble is created on the desktop, and the text is received through a plain text stream)
                break;

            case 'ENDREPLY':
                // Agent reply ends (data = Agent ID)
                break;

            case 'ENDCHAT':
                // This round of chat is complete
                onEndChat();
                break;

            case 'MCPTOOLUSE':
                // MCP tool call (including skills/workflow)
                log.info('MCPTOOLUSE detail', {
                    id: data?.id,
                    name: data?.name,
                    skillOrWorkflow: data?.skill_or_workflow_name,
                });
                onProgress({
                    type: 'tool_start',
                    tool: data?.name || 'mcp_tool',
                    args: data?.args || data,
                    description: `调用工具: ${data?.skill_or_workflow_name || data?.name || 'unknown'}`,
                });
                break;

            case 'WITHMCPTOOLFILES':
                // User Supplementary Document Confirmation (Skills/Workflows)
                break;

            case 'WITHWFSTATUS':
                // Workflow execution status update
                if (data?.status) {
                    log.info('Workflow status', { id: data.id, status: data.status.status });
                }
                break;

            case 'WITHMCPTOOLRESULT':
                // MCP tool execution results
                onProgress({
                    type: 'tool_result',
                    tool: `tool_${data?.id || 'unknown'}`,
                    result: data?.result || data,
                });
                // Skill/workflow results may contain generated files (result.file_list); emit them as artifacts
                {
                    const rawResult = data?.result;
                    let parsed: any = undefined;
                    if (typeof rawResult === 'string') {
                        try { parsed = JSON.parse(rawResult); } catch { parsed = undefined; }
                    } else if (rawResult && typeof rawResult === 'object') {
                        parsed = rawResult;
                    }
                    // DIAGNOSTIC: dump the raw result structure to understand where generated files live
                    log.info('WITHMCPTOOLRESULT detail', {
                        id: data?.id,
                        resultType: typeof rawResult,
                        parsedKeys: parsed && typeof parsed === 'object' ? Object.keys(parsed) : null,
                        rawPreview: typeof rawResult === 'string' ? rawResult.slice(0, 800) : undefined,
                    });
                    const fileList = parsed?.file_list;
                    if (Array.isArray(fileList) && fileList.length > 0) {
                        const files = fileList
                            .filter((f: any) => f && typeof f.file_path === 'string')
                            .map((f: any) => ({ name: String(f.file_name || ''), url: String(f.file_path) }));
                        if (files.length > 0) {
                            log.info('Skill/workflow produced files', { count: files.length });
                            onProgress({ type: 'cloud_files', files });
                        }
                    }
                }
                break;

            case 'STOPPABLE':
                // Whether this round of chat can be stopped (ignored)
                break;

            case 'TITLE':
                // Chat room title update (desktop can be used to update session title)
                if (data) {
                    log.info('Chat title received', { title: data });
                }
                break;

            case 'TRUNCATABLE':
                // Whether chat room memory can be cleared (ignored)
                break;

            case 'TRUNCATEOK':
                // Clear memory successfully confirmed (ignored)
                break;

            case 'THINKING':
                // Thought mode status (ignored)
                break;

            case 'ENABLETHINKING':
                // Enable think mode (internal command, ignored)
                break;

            case 'IMGGEN':
                // Image generation mode status (ignored)
                break;

            case 'ERROR':
                log.error('OpenFlux chat error', { data });
                onError();
                break;

            default:
                log.warn(`Unknown NexusAI command: ${cmd}`, { data });
                break;
        }
    }

    /** Process the next request in the queue */
    private processNextInQueue(conn: ChatroomConnection): void {
        conn.busy = false;

        if (conn.queue.length > 0) {
            const next = conn.queue.shift()!;
            log.info(`Processing next queued request (remaining: ${conn.queue.length})`);
            this.executeChat(conn, next);
        }
    }

    /** Destroy all connections (called when closing) */
    destroy(): void {
        for (const [chatroomId, conn] of this.connections) {
            try { conn.ws.close(); } catch { /* ignore */ }
        }
        this.connections.clear();
    }
}
