const zh = {
    title: '定时任务', subtitle: '让 OpenFlux 安排任务、设置提醒或监测更新', search: '搜索定时任务', search_sessions: '搜索会话', locating_run: '正在定位…', dismiss: '关闭', run_unlinked: '未找到这次运行对应的会话内容，以下是历史记录中保存的结果。', run_saved_result: '保存的运行结果', run_no_result: '这条记录没有保存结果内容。',
    all: '全部', active: '已开启', paused: '已暂停', completed: '已完成', error: '需要关注', active_detail: '活跃',
    create: '创建', create_task: '新建任务', create_chat: '通过对话创建', refresh: '刷新', mark_read: '全部标记为已读',
    suggestions: '建议', daily_title: '每日简报', daily_schedule: '工作日 8:00', daily_description: '以最新资讯和待办摘要开启每个工作日',
    daily_prompt: '每个工作日整理我关注的最新资讯和待办事项，生成简洁的每日简报。请注明来源，并突出需要我关注的变化。',
    weekly_title: '每周回顾', weekly_schedule: '星期五 16:00', weekly_description: '将一周的进展、待办与风险整理成状态更新',
    weekly_prompt: '回顾本周的工作进展，整理已完成事项、未完成任务和风险，并给出下周优先事项。请仅依据可访问的真实信息。',
    monitor_title: '跟进监控', monitor_schedule: '工作日 9:00', monitor_description: '持续跟进关注事项，及时了解值得留意的变化',
    monitor_prompt: '检查我指定的关注事项和相关资料，汇总新的进展、重要变化及需要我处理的事项。没有变化时简要说明。',
    empty: '还没有安排任务', empty_hint: '创建一个任务，让 OpenFlux 在指定时间为你工作。', no_results: '没有匹配的任务', no_results_hint: '试试其他关键词或状态筛选。',
    next_run: '下次运行', no_next: '尚未安排下次运行', run_now: '立即运行', pause: '暂停', resume: '恢复', remove: '删除', edit: '编辑任务', close: '关闭详情', back: '返回列表', more: '更多操作',
    details: '详情', runs_in: '运行于', select_chat: '选择会话', linked_chat: '关联会话', chat_after_run: '首次运行后创建会话', no_sessions: '暂无可用会话，请先新建聊天。', session_required: '请选择运行任务的会话。', workflow: '工作流', frequency: '频率', repeat: '重复',
    history: '运行历史记录', no_runs: '还没有运行记录', loading: '正在加载…', success: '已完成', failed: '运行失败', running: '正在运行', open_chat: '打开聊天', open_run: '跳转到会话中的这次运行', no_chat: '首次运行后可打开聊天',
    name: '任务名称', prompt: '任务内容', prompt_placeholder: '描述希望 OpenFlux 执行的工作，以及完成标准…', save: '保存更改', save_inline: '保存', cancel: '取消', creating: '正在保存…',
    daily: '每天', weekdays: '工作日', weekly: '每周', interval: '固定间隔', once: '仅一次', custom: '自定义', time: '时间', weekday: '星期', every: '每隔',
    minutes: '分钟', hours: '小时', days: '天', seconds: '秒', milliseconds: '毫秒', date: '运行时间', cron: 'Cron 表达式', cron_hint: '分 时 日 月 星期，例如：0 9 * * 1-5', timezone: '按本机时区运行',
    invalid_date: '请选择未来的运行时间。', invalid_interval: '请输入 10 秒至 24 天的有效间隔。', invalid_cron: '请输入五段 Cron 表达式。', invalid_time: '请选择有效时间。', required: '请填写任务名称和任务内容。',
    delete_confirm: '确定删除这个定时任务？此操作会停止后续调度。', action_failed: '操作失败，请重试。', disconnected: 'Gateway 尚未连接，请稍后重试。',
    saved: '任务已保存', triggered: '任务已开始运行', chat_create_prompt: '请帮我创建一个定时任务：', edit_schedule: '修改安排', latest: '最近运行', task_error: '连续运行失败，请检查任务内容或重新安排。', run_anchor_missing: '已打开会话，但未找到这次运行对应的内容。',
} as const;
const en: Record<keyof typeof zh, string> = {
    title: 'Scheduled tasks', subtitle: 'Let OpenFlux schedule tasks, set reminders, or monitor updates', search: 'Search scheduled tasks', search_sessions: 'Search conversations', locating_run: 'Locating…', dismiss: 'Close', run_unlinked: 'The conversation content for this run could not be found. The saved run result is shown below.', run_saved_result: 'Saved run result', run_no_result: 'This record has no saved result.',
    all: 'All', active: 'Active', paused: 'Paused', completed: 'Completed', error: 'Needs attention', active_detail: 'Active',
    create: 'Create', create_task: 'New task', create_chat: 'Create in chat', refresh: 'Refresh', mark_read: 'Mark all as read',
    suggestions: 'Suggestions', daily_title: 'Daily briefing', daily_schedule: 'Weekdays at 8:00', daily_description: 'Start each workday with the latest updates and a summary of your priorities',
    daily_prompt: 'Each weekday, compile the latest updates I follow and my outstanding tasks into a concise daily briefing. Cite sources and highlight changes that need my attention.',
    weekly_title: 'Weekly review', weekly_schedule: 'Fridays at 16:00', weekly_description: 'Turn this week’s progress, outstanding work, and risks into a status update',
    weekly_prompt: 'Review this week’s progress, completed work, outstanding tasks, and risks. Suggest priorities for next week, using only information you can access and verify.',
    monitor_title: 'Follow-up monitor', monitor_schedule: 'Weekdays at 9:00', monitor_description: 'Keep track of the things you follow and changes worth your attention',
    monitor_prompt: 'Check my specified topics and related materials. Summarize new developments, important changes, and items that need my attention. Briefly state when nothing has changed.',
    empty: 'No scheduled tasks yet', empty_hint: 'Create a task and let OpenFlux work for you at the right time.', no_results: 'No matching tasks', no_results_hint: 'Try another search or status filter.',
    next_run: 'Next run', no_next: 'No upcoming run', run_now: 'Run now', pause: 'Pause', resume: 'Resume', remove: 'Delete', edit: 'Edit task', close: 'Close details', back: 'Back to list', more: 'More actions',
    details: 'Details', runs_in: 'Runs in', select_chat: 'Select a conversation', linked_chat: 'Linked conversation', chat_after_run: 'Conversation created on first run', no_sessions: 'No conversations available. Start a chat first.', session_required: 'Select the conversation where this task should run.', workflow: 'Workflow', frequency: 'Frequency', repeat: 'Repeat',
    history: 'Run history', no_runs: 'No runs yet', loading: 'Loading…', success: 'Completed', failed: 'Failed', running: 'Running', open_chat: 'Open chat', open_run: 'Jump to this run in the conversation', no_chat: 'Chat is available after the first run',
    name: 'Task name', prompt: 'Instructions', prompt_placeholder: 'Describe what OpenFlux should do and what a successful result looks like…', save: 'Save changes', save_inline: 'Save', cancel: 'Cancel', creating: 'Saving…',
    daily: 'Daily', weekdays: 'Weekdays', weekly: 'Weekly', interval: 'Fixed interval', once: 'Once', custom: 'Custom', time: 'Time', weekday: 'Day of week', every: 'Every',
    minutes: 'Minutes', hours: 'Hours', days: 'Days', seconds: 'Seconds', milliseconds: 'Milliseconds', date: 'Run at', cron: 'Cron expression', cron_hint: 'Minute hour day month weekday, e.g. 0 9 * * 1-5', timezone: 'Uses this device’s time zone',
    invalid_date: 'Choose a future date and time.', invalid_interval: 'Enter a valid interval from 10 seconds to 24 days.', invalid_cron: 'Enter a five-field cron expression.', invalid_time: 'Choose a valid time.', required: 'Enter a task name and instructions.',
    delete_confirm: 'Delete this scheduled task? Future runs will stop.', action_failed: 'The action failed. Please try again.', disconnected: 'Gateway is not connected. Please try again shortly.',
    saved: 'Task saved', triggered: 'Task started', chat_create_prompt: 'Help me create a scheduled task: ', edit_schedule: 'Edit schedule', latest: 'Latest run', task_error: 'Repeated runs failed. Review the instructions or update the schedule.', run_anchor_missing: 'Opened the conversation, but could not find the content for this run.',
};
export type SchedulerCopyKey = keyof typeof zh;
export function schedulerCopy(locale: string, key: SchedulerCopyKey): string { return locale === 'en' ? en[key] : zh[key]; }
